application: weather-beacon
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: static/styles
- url: /images
  static_dir: static/images
- url: /scripts
  static_dir: static/scripts
- url: /key_setter.html
  static_files: static/key_setter.html
  upload: static/key_setter.html
- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: weatherbeacon.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
